### ISSUE TITLE
JSON CHECK

### ISSUE THREAD

**Issue by kanghw0325** [bytedance/Protenix#18]
Congrats with an impressive work

I wonder a bit about my JSON file.

I could not get any result from this. Actually, I could get the result from Web server.
Can you tell me how to write this `pairing_db_fpath` and `non_pairing_db_fpath`?

My json code is here

```
[{
        "sequences": [
                {"proteinChain":
                        {"count": 1,
                                "sequence": "GREDAELLVTVRGGRLRGIRLKTPGGPVSAFLGIPFAEPPMGPRRFLPPEPKQPWSGVVDATTFQSVCYQYVDTLYPGFEGTEMWNPNRELSEDCLYLNVWTPYPRPTSPTPVLVWIYGGGFYSGASSLDVYDGRFLVQAERTVLVSMNYRVGAFGFLALPGSREAPGNVGLLDQRLALQWVQENVAAFGGDPTSVTLFGESAGAASVGMHLLSPPSRGLFHRAVLQSGAPNGPWATVGMGEARRRATQLAHLVGCPPGGTGGNDTELVACLRTRPAQVLVNHEWHVLPQESVFRFSFVPVVDGDFLSDTPEALINAGDFHGLQVLVGVVKDEGSYFLVYGAPGFSKDNESLISRAEFLAGVRVGVPQVSDLAAEAVVLHYTDWLHPEDPARLREALSDVVGDHNVVCPVAQLAGRLAAQGARVYAYVFEHRASTLSWPLWMGVPHGYEIEFIFGIPLDPSRNYTAEEKIFAQRLMRYWANFARTGDPNEPRDPKAPQWPPYTAGAQQYVSLDLRPLEVRRGLRAQACAFWNRFLPKLLSAT",
                                "modifications": [],
                                "msa":{
                                        "search_tool":"jackhmmer",
                                        "pairing_db":"uniprot",
                                        "pairing_db_fpath":"/af3-dev/release_data/mmcif_msa",
                                        "non_pairing_db_fpath":"/af3-dev/release_data/mmcif_msa"
                                }
                        }
                },
                {"ligand":
                        {"count": 1,
                                "ligand": "CC(O)NC1COC(COC2OC(C)C(O)C(O)C2O)C(OC2OC(CO)C(O)C(O)C2NC(C)O)C1O"}
                }
        ],
        "name": "6CQT",
        "atom_confidence": false,
        "covalent_bonds": [
                {
                        "left_entity": 1, "left_position": 349, "left_atom": "ND2",
                        "right_entity": 2, "right_position": 1, "right_atom": "C4"
                }
        ],
        "use_msa": true,
        "model_seeds": [],
        "model_version": "v1"
}
]

```

and the error pages
```
2024-11-14 11:31:36,251 [/workspace/protenix/openfold_local/data/tools/utils.py:38] INFO root: Started Jackhmmer () query
2024-11-14 11:31:36,344 [/workspace/protenix/openfold_local/data/tools/utils.py:42] INFO root: Finished Jackhmmer () query in 0.092 seconds
2024-11-14 11:31:36,390 [/workspace/runner/inference.py:170] INFO __main__: Jackhmmer failed
stderr:
Fatal exception (source file esl_buffer.c, line 1608):
failed to slurp /af3-dev/release_data/


:
Traceback (most recent call last):
  File "/workspace/protenix/data/infer_data_pipeline.py", line 212, in __getitem__
    data, atom_array, _ = self.process_one(
  File "/workspace/protenix/data/infer_data_pipeline.py", line 115, in process_one
    InferenceMSAFeaturizer.make_msa_feature(
  File "/workspace/protenix/data/msa_featurizer.py", line 1145, in make_msa_feature
    msa_feats = InferenceMSAFeaturizer.get_inference_prot_msa_features_for_assembly(
  File "/workspace/protenix/data/msa_featurizer.py", line 1072, in get_inference_prot_msa_features_for_assembly
    msa_dirs.update(msa_parallel(msa_sequences))
  File "/workspace/protenix/data/msa_utils.py", line 1413, in msa_parallel
    results.append(future.result())
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/protenix/data/msa_utils.py", line 1390, in search_msa_paired
    search_msa(sequence, pairing_db_fpath, pairing_file)
  File "/workspace/protenix/data/msa_utils.py", line 1363, in search_msa
    _ = run_msa_tool(msa_runner, tmp_fasta_path, output_sto_path, "sto")
  File "/workspace/protenix/data/msa_utils.py", line 1330, in run_msa_tool
    result = msa_runner.query(fasta_path)[0]
  File "/workspace/protenix/openfold_local/data/tools/jackhmmer.py", line 182, in query
    return self.query_multiple([input_fasta_path], max_sequences)
  File "/workspace/protenix/openfold_local/data/tools/jackhmmer.py", line 191, in query_multiple
    single_chunk_result = self._query_chunk(
  File "/workspace/protenix/openfold_local/data/tools/jackhmmer.py", line 153, in _query_chunk
    raise RuntimeError(
RuntimeError: Jackhmmer failed
stderr:
Fatal exception (source file esl_buffer.c, line 1608):
failed to slurp /af3-dev/release_data/

```

**Comment by Kqiii** [comment]
Hi @kanghw0325 ,

If I understand your use case correctly, you want to enable online MSA (Multiple Sequence Alignment) search in your inference pipeline without relying on precomputed MSAs. In this case, the pairing_db_fpath and non_pairing_db_fpath should point to two genomic database files in a format supported by Jackhmmer, such as .fasta files. Please note that you'll need to download these database files yourself.

For example, pairing_db_fpath can be the path to the Uniprot database, while non_pairing_db_fpath could point to UniRef90. You can find instructions on how to download commonly used genomic databases [here](https://github.com/aqlaboratory/openfold/blob/main/scripts/download_alphafold_dbs.sh).

A couple of important notes:

* For pairing_db, our inference.py currently only supports the Uniprot database (as detailed [here](https://github.com/bytedance/Protenix/blob/main/runner/infer_json_format.md#proteinchain)).
* For non_pairing_db, you can use any .fasta file as your database.

Hope this helps! :)

**Comment by kanghw0325** [comment]
Hi, @Kqiii 

Thank you for your quick response!
