### ISSUE TITLE
need help to decrease allocated memory

### ISSUE THREAD

**Issue by nimrod-bio** [bytedance/Protenix#27]
first, thank you for this repo

I'm trying to predict a complex of two proteins with lengths (~1200, ~2000) and getting OutOfMemory even on an A100 with 40GBs

I looked into the dtype, but I see inference.py already uses bfloat16 by default
I also looked into Cuda Unified Memory but it's not implemented in pytorch

any other directions?
any configurations that can lower the allocation size?

traceback:
```
[/workspace/protenix/runner/inference.py:204] INFO __main__: [Rank 0] CUDA out of memory. Tried to allocate 4.97 GiB. GPU :                                          Traceback (most recent call last):
  File "/workspace/protenix/runner/inference.py", line 187, in main
    prediction = runner.predict(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/protenix/runner/inference.py", line 140, in predict
    prediction, _, _ = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                                                                                        return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/protenix/protenix/model/protenix.py", line 699, in forward
    pred_dict, log_dict, time_tracker = self.main_inference_loop(
  File "/workspace/protenix/protenix/model/protenix.py", line 322, in main_inference_loop
    pred_dict, log_dict, time_tracker = self._main_inference_loop(
  File "/workspace/protenix/protenix/model/protenix.py", line 416, in _main_inference_loop
    pred_dict["coordinate"] = self.sample_diffusion(
  File "/workspace/protenix/protenix/model/protenix.py", line 276, in sample_diffusion
    return autocasting_disable_decorator(self.configs.skip_amp.sample_diffusion)(
  File "/workspace/protenix/protenix/utils/torch_utils.py", line 119, in new_func
    return func(
  File "/workspace/protenix/protenix/model/generator.py", line 240, in sample_diffusion
    chunk_x_l = _chunk_sample_diffusion(
  File "/workspace/protenix/protenix/model/generator.py", line 208, in _chunk_sample_diffusion
    x_denoised = denoise_net(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                                                                                        return self._call_impl(*args, **kwargs)                                                                                                                                                                        File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                                                                                return forward_call(*args, **kwargs)
  File "/workspace/protenix/protenix/model/modules/diffusion.py", line 514, in forward                                                                                                                               r_update = self.f_forward(                                                                                                                                                                                     File "/workspace/protenix/protenix/model/modules/diffusion.py", line 386, in f_forward                                                                                                                             s_single, z_pair = self.diffusion_conditioning(                                                                                                                                                                File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                                                                                        return self._call_impl(*args, **kwargs)                                                                                                                                                                        File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)                                                                                                                                                                           File "/workspace/protenix/protenix/model/modules/diffusion.py", line 115, in forward                                                                                                                               pair_z = self.linear_no_bias_z(self.layernorm_z(pair_z))                                                                                                                                                       File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl                                                                                                        return self._call_impl(*args, **kwargs)                                                                                                                                                                        File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl                                                                                                                return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward                                                                                                                    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.97 GiB. GPU
```

**Comment by zhangyuxuann** [comment]
@nimrod-bio The `Diffusion Module` and `Confidence Head` is [by default inference on fp32](https://github.com/bytedance/Protenix/blob/071254b75e9d40f3678928e9aaacb3966ca05683/configs/configs_base.py#L113), can you retry it by setting as  follows:
```bash
export LAYERNORM_TYPE=fast_layernorm

N_sample=5
N_step=200
N_cycle=10
seed=101
use_deepspeed_evo_attention=true
input_json_path="./examples/example.json"
# wget -P /af3-dev/release_model/ https://af3-dev.tos-cn-beijing.volces.com/release_model/model_v1.pt
load_checkpoint_path="/af3-dev/release_model/model_v1.pt"
dump_dir="./output"

python3 runner/inference.py \
--seeds ${seed} \
--load_checkpoint_path ${load_checkpoint_path} \
--dump_dir ${dump_dir} \
--input_json_path ${input_json_path} \
--use_deepspeed_evo_attention ${use_deepspeed_evo_attention} \
--model.N_cycle ${N_cycle} \
--sample_diffusion.N_sample ${N_sample} \
--sample_diffusion.N_step ${N_step} \
--skip_amp.sample_diffusion false \
--slip_amp.confidence_head false \
```

**Comment by nimrod-bio** [comment]
thank you
It will take some time until I have a machine with A100 again
I will try your suggestions and update with the results
