### ISSUE TITLE
Issues with cuda cusparse and cuda_runtime.api

### ISSUE THREAD

**Issue by celalp** [bytedance/Protenix#28]
Hi, 

Thank you for this amazing work. I wanted to set up a conda environment to run inference with the model you provided but I keep running into issues. I've followed the steps in the Dockerfile and also in #5 but I keep getting the following error. 

```
bash inference_demo.sh 
[2024-11-15 16:31:57,365] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
Detected CUDA files, patching ldflags
Emitting ninja build file /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/build.ninja...
Building extension module fastfold_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /home/alper/miniconda3/envs/protenix/bin/x86_64-conda-linux-gnu-c++ -MMD -MF layer_norm_cuda.o.d -DTORCH_EXTENSION_NAME=fastfold_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /home/alper/miniconda3/envs/protenix/include -isystem /home/alper/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda.cpp -o layer_norm_cuda.o 
FAILED: layer_norm_cuda.o 
/home/alper/miniconda3/envs/protenix/bin/x86_64-conda-linux-gnu-c++ -MMD -MF layer_norm_cuda.o.d -DTORCH_EXTENSION_NAME=fastfold_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /home/alper/miniconda3/envs/protenix/include -isystem /home/alper/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda.cpp -o layer_norm_cuda.o 
In file included from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAGraphsC10Utils.h:3,
                 from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/c10/cuda/CUDACachingAllocator.h:4,
                 from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h:8,
                 from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAGuard.h:7,
                 from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda.cpp:15:
/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
    6 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/3] /home/alper/miniconda3/envs/protenix/bin/nvcc --generate-dependencies-with-compile --dependency-output layer_norm_cuda_kernel.cuda.o.d -ccbin /home/alper/miniconda3/envs/protenix/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fastfold_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /home/alper/miniconda3/envs/protenix/include -isystem /home/alper/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++17 -maxrregcount=50 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_90,code=sm_90 -c /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
FAILED: layer_norm_cuda_kernel.cuda.o 
/home/alper/miniconda3/envs/protenix/bin/nvcc --generate-dependencies-with-compile --dependency-output layer_norm_cuda_kernel.cuda.o.d -ccbin /home/alper/miniconda3/envs/protenix/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fastfold_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /home/alper/miniconda3/envs/protenix/include -isystem /home/alper/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++17 -maxrregcount=50 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_90,code=sm_90 -c /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda_kernel.cu -o layer_norm_cuda_kernel.cuda.o 
nvcc warning : incompatible redefinition for option 'compiler-bindir', the last value of this option was used
In file included from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:3,
                 from /home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/kernel/layer_norm_cuda_kernel.cu:26:
/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContextLight.h:7:10: fatal error: cusparse.h: No such file or directory
    7 | #include <cusparse.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/layer_norm.py", line 28, in <module>
    fastfold_layer_norm_cuda = importlib.import_module("fastfold_layer_norm_cuda")
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fastfold_layer_norm_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alper/Documents/packages/Protenix/runner/inference.py", line 32, in <module>
    from protenix.model.protenix import Protenix
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/protenix.py", line 31, in <module>
    from protenix.openfold_local.model.primitives import LayerNorm
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/openfold_local/model/primitives.py", line 41, in <module>
    from protenix.model.layer_norm.layer_norm import FusedLayerNorm
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/__init__.py", line 16, in <module>
    from .layer_norm import FusedLayerNorm
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/layer_norm.py", line 33, in <module>
    fastfold_layer_norm_cuda = compile(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/protenix/model/layer_norm/torch_ext_compile.py", line 23, in compile
    return load(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/alper/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fastfold_layer_norm_cuda'
```

All the necessary cuda stuff is installed and are in the conda environment but the compiler can't seem to be able to find them. 

Thanks, 
Alper

**Comment by yangyanpinghpc** [comment]
1. verify whether you have installed CUDA.
2. check whether the CUDA_HOME environment variable has been set. ( export CUDA_HOME=/usr/local/cuda )
