### ISSUE TITLE
Error when only predicting ligand

### ISSUE THREAD

**Issue by v-shaoningli** [bytedance/Protenix#35]
Hi! I wanna only predict the ligand structure, but proteinix raised errors:

```bash
Traceback (most recent call last):
  File "/workspace/runner/inference.py", line 213, in main
    runner.dumper.dump(
  File "/workspace/runner/dumper.py", line 74, in dump
    self.dump_predictions(
  File "/workspace/runner/dumper.py", line 107, in dump_predictions
    self._save_structure(
  File "/workspace/runner/dumper.py", line 135, in _save_structure
    save_structure_cif(
  File "/workspace/protenix/data/utils.py", line 181, in save_structure_cif
    save_atoms_to_cif(
  File "/workspace/protenix/data/utils.py", line 154, in save_atoms_to_cif
    cifwriter.save_to_cif(
  File "/workspace/protenix/data/utils.py", line 288, in save_to_cif
    block_dict.update(self._get_entity_poly_and_entity_poly_seq_block())
  File "/workspace/protenix/data/utils.py", line 260, in _get_entity_poly_and_entity_poly_seq_block
    "entity_poly": pdbx.CIFCategory(entity_poly),
  File "/opt/conda/lib/python3.10/site-packages/biotite/structure/io/pdbx/cif.py", line 327, in __init__
    columns = {
  File "/opt/conda/lib/python3.10/site-packages/biotite/structure/io/pdbx/cif.py", line 328, in <dictcomp>
    key: CIFColumn(col) if not isinstance(col, CIFColumn) else col
  File "/opt/conda/lib/python3.10/site-packages/biotite/structure/io/pdbx/cif.py", line 138, in __init__
    data = CIFData(data, str)
  File "/opt/conda/lib/python3.10/site-packages/biotite/structure/io/pdbx/cif.py", line 66, in __init__
    self._array = _arrayfy(array)
  File "/opt/conda/lib/python3.10/site-packages/biotite/structure/io/pdbx/cif.py", line 1061, in _arrayfy
    raise ValueError("Array must contain at least one element")
ValueError: Array must contain at least one element
```

The json file is:
```
[
    {
        "sequences": [
            {
                "ligand": {
                    "ligand": "COc1cc(OC)ccc1/C=C/N(C(=O)C)C",
                    "count": 1
                }
            }
        ],
        "modelSeeds": [],
        "assembly_id": "1",
        "name": "LIG_1"
    }
]

```

**Comment by cloverzizi** [comment]
Hi Shaoning, 

This issue has been resolved in the recent code update. The task results without polymer can now be saved normally. 
Thank you for the feedback :D

**Comment by v-shaoningli** [comment]
Thanks for the update!
