### ISSUE TITLE
Exception: Given checkpoint path not exist [/af3-dev/release_model/model_v0.2.0.pt]

### ISSUE THREAD

**Issue by chen10089** [bytedance/Protenix#38]
When I run the script:
protenix predict --input examples/example.json --out_dir  ./output --seeds 101

Then I get the result:
2024-12-14 21:39:35,885 [/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/batch_inference.py:353] INFO runner.batch_inference: run infer with input=examples/example.json, out_dir=./output, use_msa_server=False
2024-12-14 21:39:35,885 [/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/batch_inference.py:254] INFO runner.batch_inference: will infer with 1 jsons
2024-12-14 21:39:35,894 [/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/inference.py:152] INFO runner.inference: Distributed environment: world size: 1, global rank: 0, local rank: 0
2024-12-14 21:39:35,894 [/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/inference.py:62] INFO root: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-12-14 21:39:35,894 [/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/inference.py:86] INFO root: Finished init ENV.
train scheduler 16.0
inference scheduler 16.0
Diffusion Module has 16.0
Traceback (most recent call last):
  File "/home/chenancheng/miniconda3/envs/protenix/bin/protenix", line 8, in <module>
    sys.exit(protenix_cli())
             ^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/batch_inference.py", line 357, in predict
    inference_jsons(input, out_dir, use_msa_server, seeds=seeds)
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/batch_inference.py", line 261, in inference_jsons
    runner = get_default_runner(seeds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/batch_inference.py", line 227, in get_default_runner
    return InferenceRunner(configs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/inference.py", line 48, in __init__
    self.load_checkpoint()
  File "/home/chenancheng/miniconda3/envs/protenix/lib/python3.11/site-packages/runner/inference.py", line 100, in load_checkpoint
    raise Exception(f"Given checkpoint path not exist [{checkpoint_path}]")
Exception: Given checkpoint path not exist [/af3-dev/release_model/model_v0.2.0.pt]

**Comment by chen10089** [comment]
I create a new conda env，solve the problem.
