### ISSUE TITLE
Request for conda environment

### ISSUE THREAD

**Issue by jinungsong** [bytedance/Protenix#5]
Hi, I want to try Protenix for my project.
As our lab cluster does not use docker, I should set up conda env for protenix. 

So, would you let me know if the requirements.txt for setup conda env is available?

**Comment by zhangyuxuann** [comment]
Hi, @jinungsong , I think you can refer to Dockerfile to write the requirements.txt like this:
```
torch==2.3.1 --index-url https://download.pytorch.org/whl/cu121
torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cu121
torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
dm-tree==0.1.6
rdkit==2023.03.1
biopython==1.83
modelcif==0.7
biotite==1.0.1
gemmi==0.6.5
pdbeccdutils==0.8.5
scikit-learn==1.2.2
scikit-learn-extra
deepspeed==0.14.4
protobuf==3.20.2
numpy==1.26.3
matplotlib==3.9.2
ipywidgets
py3Dmol
scipy
ml_collections
tqdm
pandas
icecream
ipdb
wandb
```
if GPU like H20 is used, maybe add another command `pip install nvidia-cublas-cu12==12.4.5.8 --no-deps`

**Comment by HannesStark** [comment]
This worked for me. Maybe it makes sense to add to the readme.

```
conda create -n protenix python=3.10

pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
pip install scipy ml_collections tqdm pandas dm-tree==0.1.6 rdkit=="2023.03.01"
pip install biopython==1.83 modelcif==0.7
pip install biotite==1.0.1 gemmi==0.6.5 pdbeccdutils==0.8.5 scikit-learn==1.2.2 scikit-learn-extra deepspeed==0.14.4 protobuf==3.20.2 tos icecream ipdb wandb numpy==1.26.3 matplotlib==3.9.2 ipywidgets py3Dmol
```

**Comment by jinungsong** [comment]
Thanks a lot!

**Comment by celalp** [comment]
This seems to be missing cuda stuff like cuda libraries and nvcc, can someone please dump an env.yaml if you managed to get conda working? Thanks

**Comment by ilovesdu** [comment]
Thank you, I have set up my environment following your instructions. But I have encountered a new problem. Could you please tell me how to solve it?
sys.path: ['/mnt/d/AI+Antibody_Design/protenix', '/mnt/d/AI+Antibody_Design/protenix/runner', '/home/sunnysdupku/miniforge3/envs/protenix/lib/python310.zip', '/home/sunnysdupku/miniforge3/envs/protenix/lib/python3.10', '/home/sunnysdupku/miniforge3/envs/protenix/lib/python3.10/lib-dynload', '/home/sunnysdupku/miniforge3/envs/protenix/lib/python3.10/site-packages']
[2024-11-22 10:32:05,248] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
2024-11-22 10:32:06,918 [/mnt/d/AI+Antibody_Design/protenix/runner/inference.py:166] INFO __main__: Distributed environment: world size: 1, global rank: 0, local rank: 0
2024-11-22 10:32:06,918 [/mnt/d/AI+Antibody_Design/protenix/runner/inference.py:76] INFO root: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-11-22 10:32:06,918 [/mnt/d/AI+Antibody_Design/protenix/runner/inference.py:166] INFO __main__: env: None
Traceback (most recent call last):
  File "/mnt/d/AI+Antibody_Design/protenix/runner/inference.py", line 246, in <module>
    main(configs)
  File "/mnt/d/AI+Antibody_Design/protenix/runner/inference.py", line 171, in main
    runner = InferenceRunner(configs)
  File "/mnt/d/AI+Antibody_Design/protenix/runner/inference.py", line 59, in __init__
    self.init_env()
  File "/mnt/d/AI+Antibody_Design/protenix/runner/inference.py", line 88, in init_env
    env is not None
AssertionError: if use ds4sci, set env as https://www.deepspeed.ai/tutorials/ds4sci_evoformerattention/

**Comment by zhangyuxuann** [comment]
Hi @ilovesdu, if you do not use our docker image, you can set this as indicated in [README.md](README.md)
```bash
git clone -b v3.5.1 https://github.com/NVIDIA/cutlass.git  /path/to/cutlass
export CUTLASS_PATH=/path/to/cutlass
```

**Comment by zaixizhang** [comment]
I tried to set the cutlass as indicated in README.md, but still encountered error:

2024-11-26 05:11:01,631 [/n/holylabs/LABS/mzitnik_lab/Users/zaixizhang/Protenix/runner/inference.py:179] INFO __main__: [Rank 0 (3/3)] 7pzb: N_asym 8, N_token 600, N_atom 5222, N_msa 6502
Using /n/home09/zaixizhang/.cache/torch_extensions/py310_cu124 as PyTorch extensions root...
No modifications detected for re-loaded extension module evoformer_attn, skipping build step...
Loading extension module evoformer_attn...
2024-11-26 05:11:01,810 [/n/holylabs/LABS/mzitnik_lab/Users/zaixizhang/Protenix/runner/inference.py:204] INFO __main__: [Rank 0]7pzb /n/home09/zaixizhang/.cache/torch_extensions/py310_cu124/evoformer_attn/evoformer_attn.so: cannot open shared object file: No such file or directory:
Traceback (most recent call last):
  File "/n/holylabs/LABS/mzitnik_lab/Users/zaixizhang/Protenix/runner/inference.py", line 187, in main
    prediction = runner.predict(data)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/n/holylabs/LABS/mzitnik_lab/Users/zaixizhang/Protenix/runner/inference.py", line 140, in predict
    prediction, _, _ = self.model(
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/protenix.py", line 695, in forward
    pred_dict, log_dict, time_tracker = self.main_inference_loop(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/protenix.py", line 322, in main_inference_loop
    pred_dict, log_dict, time_tracker = self._main_inference_loop(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/protenix.py", line 383, in _main_inference_loop
    s_inputs, s, z = self.get_pairformer_output(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/protenix.py", line 191, in get_pairformer_output
    z = self.msa_module(
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/modules/pairformer.py", line 733, in forward
    msa_sample, z = checkpoint_blocks(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/utils/checkpointing.py", line 85, in checkpoint_blocks
    return exec(blocks, args)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/utils/checkpointing.py", line 72, in exec
    a = wrap(block(*a))
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/modules/pairformer.py", line 518, in forward
    _, z = self.pair_stack(
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/model/modules/pairformer.py", line 133, in forward
    z += self.tri_att_start(
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/model/triangular_attention.py", line 129, in forward
    x = self._chunk(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/model/triangular_attention.py", line 74, in _chunk
    return chunk_layer(
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/utils/chunk_utils.py", line 285, in chunk_layer
    output_chunk = layer(**chunks)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/model/primitives.py", line 560, in forward
    o = _deepspeed_evo_attn(q, k, v, biases)
  File "/n/holylabs/LABS/lab/Users/zaixizhang/Protenix/runner/protenix/openfold_local/model/primitives.py", line 730, in _deepspeed_evo_attn
    o = DS4Sci_EvoformerAttention(q, k, v, biases)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/deepspeed4science/evoformer_attn.py", line 106, in DS4Sci_EvoformerAttention
    return EvoformerFusedAttention.apply(Q, K, V, biases[0], biases[1])
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/deepspeed4science/evoformer_attn.py", line 71, in forward
    o, lse = _attention(q, k, v, bias1_, bias2_)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/deepspeed4science/evoformer_attn.py", line 24, in _attention
    kernel_ = EvoformerAttnBuilder().load()
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 508, in load
    return self.jit_load(verbose)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 555, in jit_load
    op_module = load(name=self.name,
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1746, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2140, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /n/home09/zaixizhang/.cache/torch_extensions/py310_cu124/evoformer_attn/evoformer_attn.so: cannot open shared object file: No such file or directory

**Comment by zaixizhang** [comment]
It is due to the deepspeed compilation failure: Using /n/home09/zaixizhang/.cache/torch_extensions/py310_cu124 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /n/home09/zaixizhang/.cache/torch_extensions/py310_cu124/evoformer_attn/build.ninja...
/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module evoformer_attn...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /n/sw/helmod-rocky8/apps/Core/cuda/12.4.1-fasrc01/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output attention_cu.cuda.o.d -ccbin /n/sw/helmod-rocky8/apps/Core/gcc/9.5.0-fasrc01/bin/gcc -DTORCH_EXTENSION_NAME=evoformer_attn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/cutlass/include -I/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/cutlass/tools/util/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /n/sw/helmod-rocky8/apps/Core/cuda/12.4.1-fasrc01/cuda/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ --threads=8 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DGPU_ARCH=80 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -c /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/attention_cu.cu -o attention_cu.cuda.o 
FAILED: attention_cu.cuda.o 
/n/sw/helmod-rocky8/apps/Core/cuda/12.4.1-fasrc01/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output attention_cu.cuda.o.d -ccbin /n/sw/helmod-rocky8/apps/Core/gcc/9.5.0-fasrc01/bin/gcc -DTORCH_EXTENSION_NAME=evoformer_attn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/cutlass/include -I/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/cutlass/tools/util/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/TH -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/torch/include/THC -isystem /n/sw/helmod-rocky8/apps/Core/cuda/12.4.1-fasrc01/cuda/include -isystem /n/home09/zaixizhang/miniconda3/envs/protenix/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 --use_fast_math -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ --threads=8 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DGPU_ARCH=80 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -c /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/attention_cu.cu -o attention_cu.cuda.o 
In file included from /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/attention_cu.cu:8:
/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/gemm_kernel_utils.h:40:10: fatal error: cutlass/arch/mma.h: No such file or directory
   40 | #include "cutlass/arch/mma.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/attention_cu.cu:8:
/n/home09/zaixizhang/miniconda3/envs/protenix/lib/python3.10/site-packages/deepspeed/ops/csrc/deepspeed4science/evoformer_attn/gemm_kernel_utils.h:40:10: fatal error: cutlass/arch/mma.h: No such file or directory
   40 | #include "cutlass/arch/mma.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
fatal   : Could not open input file /tmp/tmpxft_00325594_00000000-7_attention_cu.cpp1.ii
