### ISSUE TITLE
How to get seq_to_pdb_index.json when fine-tuning

### ISSUE THREAD

**Issue by bestz123** [bytedance/Protenix#7]
Traceback (most recent call last):
  File "/workspace/./runner/train.py", line 569, in <module>
    main()
  File "/workspace/./runner/train.py", line 564, in main
    trainer = AF3Trainer(configs)
  File "/workspace/./runner/train.py", line 57, in __init__
    self.init_data()
  File "/workspace/./runner/train.py", line 187, in init_data
    self.train_dl, self.test_dls = get_dataloaders(
  File "/workspace/protenix/data/dataloader.py", line 319, in get_dataloaders
    train_dataset, test_datasets = get_datasets(configs, error_dir)
  File "/workspace/protenix/data/dataset.py", line 1069, in get_datasets
    dataset_param = _get_dataset_param(
  File "/workspace/protenix/data/dataset.py", line 1053, in _get_dataset_param
    "msa_featurizer": get_msa_featurizer(configs, dataset_name, stage),
  File "/workspace/protenix/data/dataset.py", line 820, in get_msa_featurizer
    return MSAFeaturizer(
  File "/workspace/protenix/data/msa_featurizer.py", line 653, in __init__
    self.prot_msa_featurizer = PROTMSAFeaturizer(**prot_msa_args)
  File "/workspace/protenix/data/msa_featurizer.py", line 323, in __init__
    with open(seq_to_pdb_idx_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/af3-dev/release_data/seq_to_pdb_index.json'

Hello, I encountered this problem when fine-tuning the model using my own dataset. How should I get the corresponding seq_to_pdb_index.json?

**Comment by zhangyuxuann** [comment]
Hi @bestz123, the wwPDB training data will be released in the next few days，maybe 1-2 days.

**Comment by Kqiii** [comment]
Hi @bestz123，

The seq_to_pdb_index.json file is essentially a mapping that links a protein sequence to a unique index. This index allows us to identify the directory where the Multiple Sequence Alignments (MSAs) for that sequence are stored. For example, if your dataset includes two protein sequences, seq_1 and seq_2, your seq_to_pdb_index.json might look like this:
```json
{
    "seq_1": 0,
    "seq_2": 1,
}
```
With this mapping, you can organize your MSA files in a directory structure like this:
```
root_directory_for_all_msas
├── 0
│   ├── database1_hits.a3m
│   ├── database2_hits.a3m
│   └── ...
├── 1
│   ├── database1_hits.a3m
│   ├── database2_hits.a3m
│   └── ...

``` 

Note that the index assignments are arbitrary; they are simply used for addressing the sequences.

By the way, we've released our data (please see README), and you're welcome to check out our seq_to_pdb_index.json as well as the other prepared data files.

Hope this helps!

**Comment by bestz123** [comment]
Thank you very much. I can now fine-tune the model on my own dataset, but I have two questions.
Question 1:
In finetune_demo.sh, what is the purpose of these two lines of code? When I comment out the second line, the code can run smoothly.
--load_checkpoint_path ${checkpoint_path} \
--load_checkpoint_ema_path ${checkpoint_path} \
Question 2:
When fine-tuning the model, I encountered such a problem. What caused it?
Traceback (most recent call last): File "/workspace/protenix/data/dataset.py", line 301, in __getitem__ data = self.process_one(idx) File "/workspace/protenix/data/dataset.py", line 478, in process_one ) = self.crop( File "/workspace/protenix/data/dataset.py", line 561, in crop return DataPipeline.crop( File " /workspace/protenix/data/data_pipeline.py", line 254, in crop msa_features = DataPipeline.get_msa_raw_features( File "/workspace/protenix/data/data_pipeline.py", line 130, in get_msa_raw_features msa_feats = msa_featurizer( File "/workspace/protenix/data/msa_featurizer.py", line 675, in __call__ prot_msa_feats = self.prot_msa_featurizer.get_msa_features_for_assembly( File "/workspace/protenix/data/msa_featurizer.py", line 490, in get_msa_features_for_assembly np_example = self.get_m sa_pipeline( File "/workspace/protenix/data/msa_featurizer.py", line 256, in get_msa_pipeline sequence_feat = self.process_single_sequence( File "/workspace/protenix/data/msa_featurizer.py", line 399, in process_single_sequence path := self.get_msa_path(db_name, sequence, pdb_id) File "/workspace/protenix/data/msa_featurizer.py", line 363, in get_msa_path pdb_index = self.seq_to_pdb_idx[sequence] KeyError: 'YKKALKKLAKLL' Traceback (most recent call last): File "/workspace/protenix/data/dataset.py", line 301, in __getitem__ data = self.process_ one(idx) File "/workspace/protenix/data/dataset.py", line 478, in process_one ) = self.crop( File "/workspace/protenix/data/dataset.py", line 561, in crop return DataPipeline.crop( File "/workspace/protenix/data/data_pipeline.py", line 254, in crop msa_features = DataPipeline.get_msa_raw_features( File "/workspace/protenix/data/data_pipeline.py", line 130, in get_msa_raw_features msa_featurizer( File "/workspace/protenix/data/msa_featurizer.py", line 675, in __call__ prot_msa_feats = self.prot_msa_featurizer.get_ msa_features_for_assembly( File "/workspace/protenix/data/msa_featurizer.py", line 490, in get_msa_features_for_assembly np_example = self.get_msa_pipeline( File "/workspace/protenix/data/msa_featurizer.py", line 256, in get_msa_pipeline sequence_feat = self.process_single_sequence( File "/workspace/protenix/data/msa_featurizer.py", line 399, in process_single_sequence path := self.get_msa_path(db_name, sequence, pdb_id) File "/workspace/protenix/data/msa_featurizer.py", line 363, in get_msa_path pdb_index = self.seq_to_ pdb_idx[sequence] KeyError: 'YKKALKKLAKLL'

**Comment by Kqiii** [comment]
Hi @bestz123,

A1. These two lines allow you to load our pretrained checkpoints, which you can then use as a starting point for your fine-tuning process. You can find the release checkpoints [here](https://github.com/bytedance/Protenix#model-checkpoints).

A2. May I ask whether you are using our provided seq_to_pdb_idx.json file, or have you prepared your own? If you're using ours, please note that it only contains sequences from the wwPDB. If you're using your own file, please ensure it contains a "full mapping," meaning it should include all of your sequences.

**Comment by bestz123** [comment]
Hi@Kqiii，Thank you very much for your answer. I am using the seq_to_pdb_idx.json you provided. I have removed the pdbid that caused the error. Now I encounter the following problem. How should I solve it?
Traceback (most recent call last):█████████████████████████████████████████████████████▍                                                                                                                        | 125/308 [44:37<1:35:28, 31.30s/it]
  File "/workspace/./runner/train.py", line 569, in <module>
    main()
  File "/workspace/./runner/train.py", line 565, in main
    trainer.run()
  File "/workspace/./runner/train.py", line 536, in run
    self.evaluate()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/./runner/train.py", line 324, in evaluate
    self._evaluate()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/./runner/train.py", line 368, in _evaluate
    batch, _ = self.model_forward(batch, mode=mode)
  File "/workspace/./runner/train.py", line 278, in model_forward
    batch["pred_dict"], batch["label_dict"], log_dict = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/protenix/model/protenix.py", line 718, in forward
    pred_dict, log_dict, time_tracker = self.main_inference_loop(
  File "/workspace/protenix/model/protenix.py", line 322, in main_inference_loop
    pred_dict, log_dict, time_tracker = self._main_inference_loop(
  File "/workspace/protenix/model/protenix.py", line 465, in _main_inference_loop
    pred_dict, log_dict = symmetric_permutation.permute_inference_pred_dict(
  File "/workspace/protenix/utils/permutation/permutation.py", line 473, in permute_inference_pred_dict
    pred_dict = self.permute_heads(
  File "/workspace/protenix/utils/permutation/permutation.py", line 415, in permute_heads
    pred_dict[key][..., i, :, :, :] = pred_dict[key][
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by zhangyuxuann** [comment]
This problem has been fixed in commit (https://github.com/bytedance/Protenix/commit/071254b75e9d40f3678928e9aaacb3966ca05683)
